name = "TreeHydro"
uuid = "18f621c7-d3c4-4697-8f68-54143cdddff7"
version = "0.1.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
OrdinaryDiffEqSSPRK = "669c94d9-1f4b-4b64-b377-1aa079aa2388"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
TreeAMR = "91bc416d-811c-44c1-9bc4-b9c8bbdbbd08"

[sources]
TreeAMR = {rev = "main", url = "https://github.com/eschnett/TreeAMR.jl"}

[compat]
KernelAbstractions = "0.9.42, 1"
OrdinaryDiffEqSSPRK = "2.3.2"
SciMLBase = "3.50.1"
TreeAMR = "0.1.1"
julia = "1.10"
